[package]
name = "benching"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
flurry = "0.5.2"
rayon = "1.11.0"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "benching"
harness = false